service: equation-finder

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-west-1
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:dynamodb:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/*"
package:
  individually: true

functions:
  search:
    handler: search.lambda_handler
    events:
      - http:
          method: get
          path: /equations
          request:
            parameters:
              querystrings:
                variables: true
    package:
      exclude:
        - ./**
      include:
        - ./search.py

custom:
  pythonRequirements:
    slim: true

plugins:
  - serverless-python-requirements
  - serverless-offline
